import { InitialRowData } from "../../shared/api/types";

export const initialData: InitialRowData[] = [
  {
    id: 86975,
    rowName: "Южная строительная площадка",
    total: 0,
    salary: 20300,
    mimExploitation: 0,
    machineOperatorSalary: 0,
    materials: 0,
    mainCosts: 0,
    supportCosts: 0,
    equipmentCosts: 1750,
    overheads: 108,
    estimatedProfit: 1209122,
    child: [],
  },
  {
    id: 86976,
    rowName: "Северная строительная площадка",
    total: 2,
    salary: 40945,
    mimExploitation: 0,
    machineOperatorSalary: 0,
    materials: 0,
    mainCosts: 0,
    supportCosts: 0,
    equipmentCosts: 3500,
    overheads: 0,
    estimatedProfit: 2418244,
    child: [
      {
        id: 86977,
        rowName: "Фундаментальные работы",
        total: 4,
        salary: 101500,
        mimExploitation: 0,
        machineOperatorSalary: 0,
        materials: 0,
        mainCosts: 0,
        supportCosts: 0,
        equipmentCosts: 8750,
        overheads: 0,
        estimatedProfit: 6045610,
        child: [
          {
            id: 86979,
            rowName: "Статья работы № 2",
            total: 0,
            salary: 20300,
            mimExploitation: 0,
            machineOperatorSalary: 0,
            materials: 0,
            mainCosts: 0,
            supportCosts: 0,
            equipmentCosts: 1750,
            overheads: 0,
            estimatedProfit: 1209122,
            child: [],
          },
          {
            id: 86980,
            rowName: "Статья работы № 3",
            total: 0,
            salary: 20300,
            mimExploitation: 0,
            machineOperatorSalary: 0,
            materials: 0,
            mainCosts: 0,
            supportCosts: 0,
            equipmentCosts: 1750,
            overheads: 0,
            estimatedProfit: 1209122,
            child: [],
          },
          {
            id: 86978,
            rowName: "Статья работы № 1",
            total: 0,
            salary: 20300,
            mimExploitation: 0,
            machineOperatorSalary: 0,
            materials: 0,
            mainCosts: 0,
            supportCosts: 0,
            equipmentCosts: 1750,
            overheads: 0,
            estimatedProfit: 1209122,
            child: [],
          },
          {
            id: 86981,
            rowName: "Прочие работы",
            total: 0,
            salary: 20300,
            mimExploitation: 0,
            machineOperatorSalary: 0,
            materials: 0,
            mainCosts: 0,
            supportCosts: 0,
            equipmentCosts: 1750,
            overheads: 0,
            estimatedProfit: 1209122,
            child: [],
          },
        ],
      },
      {
        id: 86982,
        rowName: "Прочие работы",
        total: 1,
        salary: 40600,
        mimExploitation: 0,
        machineOperatorSalary: 0,
        materials: 0,
        mainCosts: 0,
        supportCosts: 0,
        equipmentCosts: 3500,
        overheads: 0,
        estimatedProfit: 2418244,
        child: [
          {
            id: 87200,
            rowName: "Установка монтаж",
            total: 0,
            salary: 20300,
            mimExploitation: 0,
            machineOperatorSalary: 0,
            materials: 0,
            mainCosts: 0,
            supportCosts: 0,
            equipmentCosts: 1750,
            overheads: 0,
            estimatedProfit: 1209122,
            child: [],
          },
        ],
      },
    ],
  },
];
